{...}: {
  flake.modules.shared.shell = {
    envVars = {
      LD_LIBRARY_PATH = "/run/opengl-driver/lib";
      NIXOS_OZONE_WL = "1";
      FZF_DEFAULT_COMMAND = "fd --mount --type f --strip-cwd-prefix --hidden --exclude .git";
      FZF_CTRL_T_COMMAND = "$FZF_DEFAULT_COMMAND";
      FZF_DEFAULT_OPTS = "--color 'fg:#bbccdd,fg+:#ddeeff,bg:#334455,preview-bg:#223344,border:#778899'";
      FZF_CTRL_T_OPTS = "--preview 'fzf-preview {}' --bind 'ctrl-/:change-preview-window(down|hidden|)'";
      FZF_ALT_C_OPTS = "--preview 'tree -C {}'";
      FZF_TMUX_OPTS = "";
      FZF_TMUX = 0;
      MANPAGER = "sh -c 'col -bx | bat -l man --style=plain --paging always'";
      MANROFFOPT = "-c";
      DO_NOT_TRACK = 1;
      DETSYS_IDS_TELEMETRY = "disabled";
      AZURE_CORE_COLLECT_TELEMETRY = 0;
      SAM_CLI_TELEMETRY = 0;
      GATSBY_TELEMETRY_DISABLED = 1;
      HOMEBREW_NO_ANALYTICS = 1;
      STNOUPGRADE = 1;
      DOTNET_CLI_TELEMETRY_OPTOUT = 1;
      NH_FLAKE = "$HOME/Projects/dancolestock/nixos";
    };
    aliases = {
      sudo = "sudo ";
      c = "cd";
      ".." = "cd ..";
      "..." = "cd ../..";
      open = "xdg-open";
      ping = "ping -c 5";
      mkdir = "mkdir -pv";
      wget = "wget -c";
      chmod = "chmod -c --preserve-root";
      chown = "chown -c --preserve-root";
      chgrp = "chgrp -c --preserve-root";
      cp = "cp --interactive --verbose --recursive --reflink=auto";
      mv = "mv --interactive --verbose";
      ln = "ln --interactive --verbose";
      rm = "rm --verbose --interactive=once --preserve-root=all";
      cpv = "rsync -ah --info=progress2";
      diff = "delta";
      cat = "bat";
      du = "dust --limit-filesystem";
      df = "duf";
      ps = "procs";
      fd = "fd --mount";
      rg = "rg --one-file-system";
      less = "less -r";
      where = "type -a";
      grep = "grep --color=auto";
      egrep = "egrep --color=auto";
      fgrep = "fgrep --color=auto";
      ls = "ls -h --group-directories-first --color=auto";
      l = "ls";
      ll = "exa -l --group-directories-first";
      la = "exa --group-directories-first -a -a";
      lla = "ll -a -a";
      laa = "lla";
      lt = "ll -s=modified";
      tmux = "direnv exec / tmux -2 new -As0 -c ~";
      untar = "tar -xvaf";
      pbcopy = "xclip -selection clipboard";
      pbpaste = "xclip -selection clipboard -o";
      sudoedit = "command sudo -E nvim";
      nvim = "nvim -w ~/.nvimkeystrokes";
      myvim = "NVIM_APPNAME=myvim nvim";
      weather = "curl -sS wttr.in|head -n -2";
      gs = "git status && git diff --stat";
      gd = "git diff";
      gc = "git commit";
      gp = "git add -p";
    };
  };
}
